"use client";
import { useCallback, useEffect, useRef } from "react";
import { useStore } from "./store";
import { computeIndicators } from "./indicators";
import { isMarketOpen } from "./utils";
import type { AISignal } from "./types";

/**
 * useAutoTradeEngine
 *
 * Evaluates signals and executes paper trades automatically.
 *
 * COST CONTROL:
 * - First tries to reuse signals already in the store (generated by manual scans).
 * - Only calls Claude directly when auto-trade is enabled AND no fresh signal exists
 *   for a ticker (fresh = < 5 minutes old). This means Claude is called at most once
 *   per ticker per 5-minute window, not every 30 seconds.
 */
export function useAutoTradeEngine() {
  const watchlist = useStore((s) => s.watchlist);
  const quotes = useStore((s) => s.quotes);
  const candlesMap = useStore((s) => s.candles);
  const news = useStore((s) => s.news);
  const tweets = useStore((s) => s.tweets);
  const anthropicKey = useStore((s) => s.anthropicKey);
  const cashBalance = useStore((s) => s.cashBalance);
  const positions = useStore((s) => s.positions);
  const signals = useStore((s) => s.signals);
  const autoTradeEnabled = useStore((s) => s.autoTradeEnabled);
  const settings = useStore((s) => s.autoTradeSettings);
  const autoTradeDailyPnl = useStore((s) => s.autoTradeDailyPnl);
  const autoTradeDailyCount = useStore((s) => s.autoTradeDailyCount);
  const autoTradeLastReset = useStore((s) => s.autoTradeLastReset);

  const executeOrder = useStore((s) => s.executeOrder);
  const addSignal = useStore((s) => s.addSignal);
  const addAutoTradeLog = useStore((s) => s.addAutoTradeLog);
  const resetAutoTradeDailyStats = useStore((s) => s.resetAutoTradeDailyStats);
  const setAutoTradeEnabled = useStore((s) => s.setAutoTradeEnabled);
  const recordAnthropicUsage = useStore((s) => s.recordAnthropicUsage);

  const lastTradeTime = useRef<Record<string, number>>({});

  // Reset daily counters at midnight
  useEffect(() => {
    const today = new Date().toISOString().split("T")[0];
    if (autoTradeLastReset !== today) resetAutoTradeDailyStats();
  }, [autoTradeLastReset, resetAutoTradeDailyStats]);

  const evaluateSignal = useCallback(
    async (ticker: string): Promise<AISignal | null> => {
      // 1. Check if there is a recent signal already in the store (< 5 min old)
      const FRESH_MS = 5 * 60 * 1000;
      const existing = signals.find(
        (s) => s.ticker === ticker && Date.now() - s.timestamp < FRESH_MS
      );
      if (existing) return existing;

      // 2. No fresh signal — call Claude, but only if API key is present
      if (!anthropicKey) return null;

      const quote = quotes[ticker];
      const candles = candlesMap[ticker];
      if (!quote || !candles?.length) return null;

      const ind = computeIndicators(candles);
      const tickerNews = news
        .filter((n) => !n.ticker || n.ticker === ticker)
        .slice(0, 3)
        .map((n) => n.headline)
        .join("; ");

      const tickerTweets = tweets.filter((t) => t.tickers.includes(ticker)).slice(0, 5);
      const xSentimentSummary = tickerTweets.length
        ? tickerTweets
            .map((t) => `${t.sentiment} (${t.likes}❤): "${t.text.slice(0, 80)}..."`)
            .join(" | ")
        : null;

      try {
        const res = await fetch("/api/ai/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            ticker,
            price: quote.price,
            vwap: ind.vwap,
            rsi: ind.rsi,
            macd: ind.macd,
            macdSignal: ind.macdSignal,
            volume: quote.volume,
            relVolume: ind.relVolume,
            prevHigh: quote.high,
            prevLow: quote.low,
            sma20: ind.sma20,
            ema9: ind.ema9,
            bbUpper: ind.bbUpper,
            bbLower: ind.bbLower,
            news: tickerNews || null,
            xSentiment: xSentimentSummary,
            apiKey: anthropicKey,
          }),
        });
        const data = await res.json();
        if (data.usage) {
          recordAnthropicUsage(data.usage.input_tokens ?? 0, data.usage.output_tokens ?? 0);
        }
        if (data.signal) {
          addSignal(data.signal);
          return data.signal;
        }
      } catch {}
      return null;
    },
    [signals, anthropicKey, quotes, candlesMap, news, tweets, addSignal, recordAnthropicUsage]
  );

  const evaluateAndTrade = useCallback(async () => {
    if (!autoTradeEnabled) return;

    // Block live auto-trade unless explicitly enabled
    const { alpacaMode, alpacaLiveKey, alpacaLiveSecret } = useStore.getState();
    const isLive = alpacaMode === "live";
    if (isLive && !settings.allowLiveAutoTrade) return;
    if (isLive && (!alpacaLiveKey || !alpacaLiveSecret)) {
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: "Live auto-trade enabled but no live Alpaca keys are set. Add them in Settings.",
      });
      return;
    }

    // Market hours gate
    if (settings.marketHoursOnly && !isMarketOpen()) return;

    // Daily circuit breakers
    if (autoTradeDailyCount >= settings.maxDailyTrades) return;
    if (autoTradeDailyPnl <= -settings.maxDailyLoss) {
      setAutoTradeEnabled(false);
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: `Daily loss limit of $${settings.maxDailyLoss} reached. Auto-trade disabled.`,
      });
      return;
    }

    const { liveAccount } = useStore.getState();
    const portfolioValue = isLive && liveAccount
      ? liveAccount.portfolioValue
      : cashBalance + positions.reduce((sum, p) => sum + p.currentPrice * p.quantity, 0);
    const availableCash = isLive && liveAccount ? liveAccount.buyingPower : cashBalance;

    for (const ticker of watchlist.slice(0, 5)) {
      // Per-ticker cooldown
      const cooldownMs = settings.cooldownMinutes * 60 * 1000;
      if (Date.now() - (lastTradeTime.current[ticker] ?? 0) < cooldownMs) continue;

      // Skip if already holding this ticker
      if (positions.find((p) => p.ticker === ticker && p.quantity > 0)) continue;

      const signal = await evaluateSignal(ticker);
      if (!signal || signal.signal === "HOLD") continue;

      // Confidence gate
      if (signal.confidence < settings.confidenceThreshold) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: `Confidence ${(signal.confidence * 100).toFixed(0)}% below threshold ${(settings.confidenceThreshold * 100).toFixed(0)}%.`,
          signal,
        });
        continue;
      }

      // Shorts gate
      if (signal.signal === "SELL" && !settings.allowShorts) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: "SELL signal skipped — shorts disabled.",
          signal,
        });
        continue;
      }

      // X confirmation gate
      if (settings.requireXConfirmation) {
        const tickerTweets = tweets.filter((t) => t.tickers.includes(ticker));
        if (tickerTweets.length > 0) {
          const bull = tickerTweets.filter((t) => t.sentiment === "bullish").length;
          const bear = tickerTweets.filter((t) => t.sentiment === "bearish").length;
          const agrees =
            (signal.signal === "BUY" && bull > bear) ||
            (signal.signal === "SELL" && bear > bull);
          if (!agrees) {
            addAutoTradeLog({
              ticker,
              decision: "SKIPPED",
              reason: `X sentiment doesn't confirm ${signal.signal} (bull:${bull} bear:${bear}).`,
              signal,
            });
            continue;
          }
        }
      }

      // Position sizing
      const riskPerShare = Math.abs(signal.entry - signal.stop_loss);
      if (riskPerShare <= 0) continue;

      let shares = Math.floor((portfolioValue * (settings.riskPerTrade / 100)) / riskPerShare);
      if (shares * signal.entry > settings.maxPositionSize)
        shares = Math.floor(settings.maxPositionSize / signal.entry);
      if (shares * signal.entry > availableCash)
        shares = Math.floor((availableCash * 0.95) / signal.entry);
      if (shares < 1) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: `Position too small (${shares} shares). Check cash balance or risk settings.`,
          signal,
        });
        continue;
      }

      // Execute — route to Alpaca in live mode, local state in paper mode
      if (isLive) {
        const { alpacaLiveKey: liveKey, alpacaLiveSecret: liveSecret } = useStore.getState();
        try {
          const res = await fetch("/api/trade/order", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              mode: "live",
              apiKey: liveKey,
              apiSecret: liveSecret,
              symbol: ticker,
              side: signal.signal === "BUY" ? "BUY" : "SELL",
              type: "MARKET",
              qty: shares,
            }),
          });
          const data = await res.json();
          if (!res.ok || data.error) {
            addAutoTradeLog({
              ticker,
              decision: "BLOCKED",
              reason: `Alpaca rejected order: ${data.error ?? "unknown error"}`,
              signal,
            });
            continue;
          }
          // Record locally for the journal
          executeOrder({
            ticker,
            side: signal.signal === "BUY" ? "BUY" : "SELL",
            type: "MARKET",
            quantity: shares,
            price: signal.entry,
            stopPrice: signal.stop_loss,
            takeProfitPrice: signal.target,
          });
        } catch (err) {
          addAutoTradeLog({
            ticker,
            decision: "BLOCKED",
            reason: `Network error submitting live order: ${err instanceof Error ? err.message : "unknown"}`,
            signal,
          });
          continue;
        }
      } else {
        executeOrder({
          ticker,
          side: signal.signal === "BUY" ? "BUY" : "SELL",
          type: "MARKET",
          quantity: shares,
          price: signal.entry,
          stopPrice: signal.stop_loss,
          takeProfitPrice: signal.target,
        });
      }

      lastTradeTime.current[ticker] = Date.now();

      addAutoTradeLog({
        ticker,
        decision: "EXECUTED",
        reason: `${signal.signal} ${shares}sh @ $${signal.entry.toFixed(2)} | Stop $${signal.stop_loss.toFixed(2)} | Target $${signal.target.toFixed(2)} | ${(signal.confidence * 100).toFixed(0)}% confidence. ${signal.reason}`,
        signal,
        sharesQty: shares,
        positionSize: shares * signal.entry,
      });
    }
  }, [
    autoTradeEnabled, settings, autoTradeDailyCount, autoTradeDailyPnl,
    watchlist, cashBalance, positions, tweets, evaluateSignal,
    executeOrder, addAutoTradeLog, setAutoTradeEnabled,
  ]);

  const monitorPositions = useCallback(() => {
    const { positions, quotes } = useStore.getState();
    for (const pos of positions) {
      if (pos.quantity <= 0) continue;
      const price = quotes[pos.ticker]?.price ?? pos.currentPrice;

      let reason: string | null = null;
      if (pos.side === "LONG") {
        if (pos.stopLoss && price <= pos.stopLoss) {
          reason = `Stop-loss triggered @ $${price.toFixed(2)} (stop $${pos.stopLoss.toFixed(2)})`;
        } else if (pos.takeProfit && price >= pos.takeProfit) {
          reason = `Take-profit triggered @ $${price.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
        }
      } else {
        if (pos.stopLoss && price >= pos.stopLoss) {
          reason = `Stop-loss triggered @ $${price.toFixed(2)} (stop $${pos.stopLoss.toFixed(2)})`;
        } else if (pos.takeProfit && price <= pos.takeProfit) {
          reason = `Take-profit triggered @ $${price.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
        }
      }

      if (reason) {
        executeOrder({
          ticker: pos.ticker,
          side: pos.side === "LONG" ? "SELL" : "BUY",
          type: "MARKET",
          quantity: pos.quantity,
          price,
        });
        addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason });
      }
    }
  }, [executeOrder, addAutoTradeLog]);

  useEffect(() => {
    if (!autoTradeEnabled) return;
    // Run every 60s (not 30s) — and only fires Claude if no fresh signal exists
    const interval = setInterval(evaluateAndTrade, 60_000);
    evaluateAndTrade(); // run once immediately on enable
    return () => clearInterval(interval);
  }, [autoTradeEnabled, evaluateAndTrade]);

  useEffect(() => {
    if (!autoTradeEnabled) return;
    // Check stop-loss / take-profit every 15 seconds
    const interval = setInterval(monitorPositions, 15_000);
    return () => clearInterval(interval);
  }, [autoTradeEnabled, monitorPositions]);
}
