"use client";
import { useCallback, useEffect, useRef } from "react";
import { useStore } from "./store";
import { computeIndicators, aggregateCandles } from "./indicators";
import { isMarketOpen } from "./utils";
import type { AISignal } from "./types";

/**
 * useAutoTradeEngine
 *
 * Evaluates signals and executes paper trades automatically.
 *
 * COST CONTROL:
 * - First tries to reuse signals already in the store (generated by manual scans).
 * - Only calls Claude directly when auto-trade is enabled AND no fresh signal exists
 *   for a ticker (fresh = < 5 minutes old). This means Claude is called at most once
 *   per ticker per 5-minute window, not every 30 seconds.
 */
export function useAutoTradeEngine() {
  const watchlist = useStore((s) => s.watchlist);
  const quotes = useStore((s) => s.quotes);
  const candlesMap = useStore((s) => s.candles);
  const news = useStore((s) => s.news);
  const tweets = useStore((s) => s.tweets);
  const anthropicKey = useStore((s) => s.anthropicKey);
  const cashBalance = useStore((s) => s.cashBalance);
  const positions = useStore((s) => s.positions);
  const signals = useStore((s) => s.signals);
  const autoTradeEnabled = useStore((s) => s.autoTradeEnabled);
  const settings = useStore((s) => s.autoTradeSettings);
  const autoTradeDailyPnl = useStore((s) => s.autoTradeDailyPnl);
  const autoTradeDailyCount = useStore((s) => s.autoTradeDailyCount);
  const autoTradeLastReset = useStore((s) => s.autoTradeLastReset);
  const trades = useStore((s) => s.trades);

  const unsettledFunds = useStore((s) => s.unsettledFunds);
  const cashAccount = useStore((s) => s.cashAccount);

  const executeOrder = useStore((s) => s.executeOrder);
  const addSignal = useStore((s) => s.addSignal);
  const addAutoTradeLog = useStore((s) => s.addAutoTradeLog);
  const resetAutoTradeDailyStats = useStore((s) => s.resetAutoTradeDailyStats);
  const setAutoTradeEnabled = useStore((s) => s.setAutoTradeEnabled);
  const recordAnthropicUsage = useStore((s) => s.recordAnthropicUsage);
  const setApiCreditError = useStore((s) => s.setApiCreditError);
  const setOutOfFundsError = useStore((s) => s.setOutOfFundsError);
  const sweepSettledFunds = useStore((s) => s.sweepSettledFunds);

  const lastTradeTime = useRef<Record<string, number>>({});
  const lastMarketClosedLog = useRef<number>(0);

  // Reset daily counters at midnight
  useEffect(() => {
    const today = new Date().toISOString().split("T")[0];
    if (autoTradeLastReset !== today) resetAutoTradeDailyStats();
  }, [autoTradeLastReset, resetAutoTradeDailyStats]);

  const evaluateSignal = useCallback(
    async (ticker: string): Promise<AISignal | null> => {
      // 1. Check if there is a recent signal already in the store (< 5 min old)
      const FRESH_MS = 5 * 60 * 1000;
      const existing = signals.find(
        (s) => s.ticker === ticker && Date.now() - s.timestamp < FRESH_MS
      );
      if (existing) return existing;

      // 2. No fresh signal — call Claude, but only if API key is present
      if (!anthropicKey) return null;

      const quote = quotes[ticker];
      const candles = candlesMap[ticker];
      if (!quote || !candles?.length) return null;

      const ind = computeIndicators(candles);

      // Multi-timeframe: aggregate 5m candles into 15m (every 3 candles)
      const candles15m = aggregateCandles(candles, 3);
      const ind15m = computeIndicators(candles15m);
      const trend15m = ind15m.macd !== undefined && ind15m.macdSignal !== undefined
        ? ind15m.macd > ind15m.macdSignal ? "bullish" : ind15m.macd < ind15m.macdSignal ? "bearish" : "neutral"
        : "N/A";

      // Recent win rate feedback loop
      const todayStart = new Date();
      todayStart.setHours(0, 0, 0, 0);
      const todayTrades = trades.filter((t) => t.exitTime >= todayStart.getTime());
      const recentWinRate = todayTrades.length > 0
        ? todayTrades.filter((t) => t.pnl > 0).length / todayTrades.length
        : 0;
      const recentTradeCount = todayTrades.length;

      const tickerNews = news
        .filter((n) => !n.ticker || n.ticker === ticker)
        .slice(0, 3)
        .map((n) => n.headline)
        .join("; ");

      const tickerTweets = tweets.filter((t) => t.tickers.includes(ticker)).slice(0, 5);
      const xSentimentSummary = tickerTweets.length
        ? tickerTweets
            .map((t) => `${t.sentiment} (${t.likes}❤): "${t.text.slice(0, 80)}..."`)
            .join(" | ")
        : null;

      try {
        const res = await fetch("/api/ai/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            ticker,
            price: quote.price,
            vwap: ind.vwap,
            rsi: ind.rsi,
            macd: ind.macd,
            macdSignal: ind.macdSignal,
            volume: quote.volume,
            relVolume: ind.relVolume,
            prevHigh: quote.high,
            prevLow: quote.low,
            sma20: ind.sma20,
            ema9: ind.ema9,
            bbUpper: ind.bbUpper,
            bbLower: ind.bbLower,
            news: tickerNews || null,
            xSentiment: xSentimentSummary,
            apiKey: anthropicKey,
            trend15m,
            rsi15m: ind15m.rsi,
            macd15m: trend15m,
            recentWinRate,
            recentTradeCount,
          }),
        });
        const data = await res.json();
        if (data.creditError) {
          setApiCreditError(true);
          return null;
        }
        if (data.usage) {
          recordAnthropicUsage(data.usage.input_tokens ?? 0, data.usage.output_tokens ?? 0);
        }
        if (data.signal) {
          // Only cache actionable signals — don't cache HOLD so it re-evaluates next cycle
          if (data.signal.signal !== "HOLD") addSignal(data.signal);
          return data.signal;
        }
      } catch {}
      return null;
    },
    [signals, anthropicKey, quotes, candlesMap, news, tweets, trades, addSignal, recordAnthropicUsage, setApiCreditError]
  );

  const evaluateAndTrade = useCallback(async () => {
    if (!autoTradeEnabled) return;

    // Block live auto-trade unless explicitly enabled
    const { alpacaMode, alpacaLiveKey, alpacaLiveSecret } = useStore.getState();
    const isLive = alpacaMode === "live";
    if (isLive && !settings.allowLiveAutoTrade) return;
    if (isLive && (!alpacaLiveKey || !alpacaLiveSecret)) {
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: "Live auto-trade enabled but no live Alpaca keys are set. Add them in Settings.",
      });
      return;
    }

    // Market hours gate
    if (settings.marketHoursOnly && !isMarketOpen()) {
      const fiveMin = 5 * 60 * 1000;
      if (Date.now() - lastMarketClosedLog.current > fiveMin) {
        lastMarketClosedLog.current = Date.now();
        addAutoTradeLog({
          ticker: "SYSTEM",
          decision: "BLOCKED",
          reason: "Market is closed. Disable 'Market Hours Only' in Settings to trade outside hours.",
        });
      }
      return;
    }

    // Daily circuit breakers
    if (autoTradeDailyCount >= settings.maxDailyTrades) return;
    if (autoTradeDailyPnl <= -settings.maxDailyLoss) {
      setAutoTradeEnabled(false);
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: `Daily loss limit of $${settings.maxDailyLoss} reached. Auto-trade disabled.`,
      });
      return;
    }

    const { liveAccount } = useStore.getState();
    const portfolioValue = isLive && liveAccount
      ? liveAccount.portfolioValue
      : cashBalance + positions.reduce((sum, p) => sum + p.currentPrice * p.quantity, 0);
    // For paper cash accounts, subtract proceeds that haven't settled yet
    const unsettledTotal = (!isLive && cashAccount)
      ? unsettledFunds.filter((f) => f.settlesAt > Date.now()).reduce((sum, f) => sum + f.amount, 0)
      : 0;
    const availableCash = isLive && liveAccount ? liveAccount.buyingPower : cashBalance - unsettledTotal;

    // Out-of-funds check
    const MIN_CASH = 100;
    if (availableCash < MIN_CASH) {
      setAutoTradeEnabled(false);
      setOutOfFundsError(true);
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: `Insufficient funds ($${availableCash.toFixed(2)} available, minimum $${MIN_CASH}). Auto-trade disabled.`,
      });
      return;
    }

    for (const ticker of watchlist.slice(0, 5)) {
      // Per-ticker cooldown
      const cooldownMs = settings.cooldownMinutes * 60 * 1000;
      if (Date.now() - (lastTradeTime.current[ticker] ?? 0) < cooldownMs) continue;

      const signal = await evaluateSignal(ticker);
      if (!signal) continue;

      if (signal.signal === "HOLD") {
        addAutoTradeLog({ ticker, decision: "SKIPPED", reason: "Signal is HOLD — no trade.", signal });
        continue;
      }

      // Skip if already holding this ticker on the same side as the signal
      const holdingSameSide = positions.find((p) =>
        p.ticker === ticker &&
        p.quantity > 0 &&
        ((signal.signal === "BUY" && p.side === "LONG") || (signal.signal === "SELL" && p.side === "SHORT"))
      );
      if (holdingSameSide) {
        addAutoTradeLog({ ticker, decision: "SKIPPED", reason: `Already holding ${holdingSameSide.side} position.`, signal });
        continue;
      }

      // Volume filter — skip thin markets
      const quote = useStore.getState().quotes[ticker];
      const candles = useStore.getState().candles[ticker];
      const ind = candles?.length ? computeIndicators(candles) : {};
      if (ind.relVolume !== undefined && ind.relVolume < 0.5) {
        addAutoTradeLog({ ticker, decision: "SKIPPED", reason: `Volume too thin (${ind.relVolume.toFixed(2)}x avg). Waiting for liquidity.`, signal });
        continue;
      }

      // Trend filter — only trade with the trend
      if (ind.sma20 && quote) {
        const aboveSma = quote.price > ind.sma20;
        if (signal.signal === "BUY" && !aboveSma) {
          addAutoTradeLog({ ticker, decision: "SKIPPED", reason: `BUY skipped — price below SMA20 ($${ind.sma20.toFixed(2)}). Counter-trend.`, signal });
          continue;
        }
        if (signal.signal === "SELL" && aboveSma) {
          addAutoTradeLog({ ticker, decision: "SKIPPED", reason: `SELL skipped — price above SMA20 ($${ind.sma20.toFixed(2)}). Counter-trend.`, signal });
          continue;
        }
      }

      // Near S/R filter — avoid entries within 0.5% of prior day high/low
      if (quote) {
        const nearHigh = Math.abs(signal.entry - quote.high) / quote.high < 0.005;
        const nearLow = Math.abs(signal.entry - quote.low) / quote.low < 0.005;
        if (nearHigh || nearLow) {
          addAutoTradeLog({ ticker, decision: "SKIPPED", reason: `Entry $${signal.entry.toFixed(2)} too close to prior day ${nearHigh ? "high" : "low"} — likely resistance/support rejection.`, signal });
          continue;
        }
      }

      // Confidence gate
      if (signal.confidence < settings.confidenceThreshold) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: `Confidence ${(signal.confidence * 100).toFixed(0)}% below threshold ${(settings.confidenceThreshold * 100).toFixed(0)}%.`,
          signal,
        });
        continue;
      }

      // Shorts gate
      if (signal.signal === "SELL" && !settings.allowShorts) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: "SELL signal skipped — shorts disabled.",
          signal,
        });
        continue;
      }

      // X confirmation gate
      if (settings.requireXConfirmation) {
        const tickerTweets = tweets.filter((t) => t.tickers.includes(ticker));
        if (tickerTweets.length > 0) {
          const bull = tickerTweets.filter((t) => t.sentiment === "bullish").length;
          const bear = tickerTweets.filter((t) => t.sentiment === "bearish").length;
          const agrees =
            (signal.signal === "BUY" && bull > bear) ||
            (signal.signal === "SELL" && bear > bull);
          if (!agrees) {
            addAutoTradeLog({
              ticker,
              decision: "SKIPPED",
              reason: `X sentiment doesn't confirm ${signal.signal} (bull:${bull} bear:${bear}).`,
              signal,
            });
            continue;
          }
        }
      }

      // Position sizing — dollar-based (supports fractional shares)
      const riskPerShare = ind.atr
        ? ind.atr * 2
        : Math.abs(signal.entry - signal.stop_loss);
      if (riskPerShare <= 0) continue;

      const drawdownFactor = autoTradeDailyPnl < -(settings.maxDailyLoss * 0.5) ? 0.5 : 1.0;

      // Compute notional $ amount, then derive fractional qty from entry price
      let notional = (portfolioValue * (settings.riskPerTrade / 100) * drawdownFactor * signal.entry) / riskPerShare;
      notional = Math.min(notional, settings.maxPositionSize, availableCash * 0.95);
      notional = Math.max(0, notional);

      if (notional < 1) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: `Position too small ($${notional.toFixed(2)}). Check cash balance or risk settings.`,
          signal,
        });
        continue;
      }

      // Fractional qty for paper; notional for live Alpaca
      const fractionalQty = +(notional / signal.entry).toFixed(4);

      // Execute — route to Alpaca in live mode, local state in paper mode
      if (isLive) {
        const { alpacaLiveKey: liveKey, alpacaLiveSecret: liveSecret } = useStore.getState();
        try {
          const res = await fetch("/api/trade/order", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              mode: "live",
              apiKey: liveKey,
              apiSecret: liveSecret,
              symbol: ticker,
              side: signal.signal === "BUY" ? "BUY" : "SELL",
              type: "MARKET",
              notional: +notional.toFixed(2),
            }),
          });
          const data = await res.json();
          if (!res.ok || data.error) {
            addAutoTradeLog({
              ticker,
              decision: "BLOCKED",
              reason: `Alpaca rejected order: ${data.error ?? "unknown error"}`,
              signal,
            });
            continue;
          }
          // Record locally for the journal using fractional qty
          executeOrder({
            ticker,
            side: signal.signal === "BUY" ? "BUY" : "SELL",
            type: "MARKET",
            quantity: fractionalQty,
            price: signal.entry,
            stopPrice: signal.stop_loss,
            takeProfitPrice: signal.target,
          });
        } catch (err) {
          addAutoTradeLog({
            ticker,
            decision: "BLOCKED",
            reason: `Network error submitting live order: ${err instanceof Error ? err.message : "unknown"}`,
            signal,
          });
          continue;
        }
      } else {
        executeOrder({
          ticker,
          side: signal.signal === "BUY" ? "BUY" : "SELL",
          type: "MARKET",
          quantity: fractionalQty,
          price: signal.entry,
          stopPrice: signal.stop_loss,
          takeProfitPrice: signal.target,
        });
      }

      lastTradeTime.current[ticker] = Date.now();

      addAutoTradeLog({
        ticker,
        decision: "EXECUTED",
        reason: `${signal.signal} ${fractionalQty}sh ($${notional.toFixed(2)}) @ $${signal.entry.toFixed(2)} | Stop $${signal.stop_loss.toFixed(2)} | Target $${signal.target.toFixed(2)} | ${(signal.confidence * 100).toFixed(0)}% confidence. ${signal.reason}`,
        signal,
        sharesQty: fractionalQty,
        positionSize: notional,
      });
    }
  }, [
    autoTradeEnabled, settings, autoTradeDailyCount, autoTradeDailyPnl,
    watchlist, cashBalance, positions, tweets, evaluateSignal,
    executeOrder, addAutoTradeLog, setAutoTradeEnabled, setOutOfFundsError,
    unsettledFunds, cashAccount,
  ]);

  const monitorPositions = useCallback(() => {
    sweepSettledFunds();
    const { positions, quotes } = useStore.getState();
    const now = Date.now();

    // End-of-day close: force-close all positions 15 min before 4pm ET
    const et = new Date(now);
    const etTime = new Date(et.toLocaleString("en-US", { timeZone: "America/New_York" }));
    const etMinutes = etTime.getHours() * 60 + etTime.getMinutes();
    const isEodClose = etMinutes >= 15 * 60 + 45 && etMinutes < 16 * 60; // 3:45–4:00 PM ET

    for (const pos of positions) {
      if (pos.quantity <= 0) continue;
      const price = quotes[pos.ticker]?.price ?? pos.currentPrice;

      // End-of-day: close everything
      if (isEodClose) {
        executeOrder({ ticker: pos.ticker, side: pos.side === "LONG" ? "SELL" : "BUY", type: "MARKET", quantity: pos.quantity, price });
        addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason: `End-of-day close @ $${price.toFixed(2)} (3:45 PM ET cutoff).` });
        continue;
      }

      // Time-based exit
      if (settings.maxPositionMinutes > 0) {
        const ageMinutes = (now - pos.entryTime) / 60000;
        if (ageMinutes >= settings.maxPositionMinutes) {
          executeOrder({ ticker: pos.ticker, side: pos.side === "LONG" ? "SELL" : "BUY", type: "MARKET", quantity: pos.quantity, price });
          addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason: `Time-based exit after ${ageMinutes.toFixed(0)} min (max ${settings.maxPositionMinutes} min).` });
          continue;
        }
      }

      // Update trailing stop
      let activeStopLoss = pos.stopLoss;
      if (settings.trailingStopPct > 0 && pos.stopLoss !== undefined) {
        const trailFactor = settings.trailingStopPct / 100;
        if (pos.side === "LONG") {
          const trailedStop = price * (1 - trailFactor);
          if (trailedStop > (pos.trailingStop ?? pos.stopLoss ?? 0)) {
            // Update trailing stop in store
            useStore.setState((s) => ({
              positions: s.positions.map((p) =>
                p.id === pos.id ? { ...p, trailingStop: trailedStop } : p
              ),
            }));
            activeStopLoss = trailedStop;
          } else {
            activeStopLoss = pos.trailingStop ?? pos.stopLoss;
          }
        } else {
          const trailedStop = price * (1 + trailFactor);
          if (trailedStop < (pos.trailingStop ?? pos.stopLoss ?? Infinity)) {
            useStore.setState((s) => ({
              positions: s.positions.map((p) =>
                p.id === pos.id ? { ...p, trailingStop: trailedStop } : p
              ),
            }));
            activeStopLoss = trailedStop;
          } else {
            activeStopLoss = pos.trailingStop ?? pos.stopLoss;
          }
        }
      }

      // Partial take-profit: sell 50% when price hits midpoint between entry and target
      if (settings.partialTpEnabled && !pos.partialTpTaken && pos.takeProfit) {
        const midpoint = pos.side === "LONG"
          ? pos.entryPrice + (pos.takeProfit - pos.entryPrice) * 0.5
          : pos.entryPrice - (pos.entryPrice - pos.takeProfit) * 0.5;
        const hitMidpoint = pos.side === "LONG" ? price >= midpoint : price <= midpoint;
        if (hitMidpoint && pos.quantity >= 2) {
          const halfQty = Math.floor(pos.quantity / 2);
          executeOrder({ ticker: pos.ticker, side: pos.side === "LONG" ? "SELL" : "BUY", type: "MARKET", quantity: halfQty, price });
          // Move stop to breakeven
          useStore.setState((s) => ({
            positions: s.positions.map((p) =>
              p.id === pos.id
                ? { ...p, partialTpTaken: true, stopLoss: pos.entryPrice, trailingStop: pos.entryPrice }
                : p
            ),
          }));
          addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason: `Partial TP: sold ${halfQty} shares @ $${price.toFixed(2)} (midpoint $${midpoint.toFixed(2)}). Stop moved to breakeven $${pos.entryPrice.toFixed(2)}.` });
          continue;
        }
      }

      // Stop-loss / take-profit check
      let reason: string | null = null;
      if (pos.side === "LONG") {
        if (activeStopLoss && price <= activeStopLoss) {
          reason = `Stop-loss triggered @ $${price.toFixed(2)} (stop $${activeStopLoss.toFixed(2)})`;
        } else if (pos.takeProfit && price >= pos.takeProfit) {
          reason = `Take-profit triggered @ $${price.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
        }
      } else {
        if (activeStopLoss && price >= activeStopLoss) {
          reason = `Stop-loss triggered @ $${price.toFixed(2)} (stop $${activeStopLoss.toFixed(2)})`;
        } else if (pos.takeProfit && price <= pos.takeProfit) {
          reason = `Take-profit triggered @ $${price.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
        }
      }

      if (reason) {
        executeOrder({ ticker: pos.ticker, side: pos.side === "LONG" ? "SELL" : "BUY", type: "MARKET", quantity: pos.quantity, price });
        addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason });
      }
    }
  }, [executeOrder, addAutoTradeLog, settings, sweepSettledFunds]);

  useEffect(() => {
    if (!autoTradeEnabled) return;
    // Run every 60s (not 30s) — and only fires Claude if no fresh signal exists
    const interval = setInterval(evaluateAndTrade, 60_000);
    evaluateAndTrade(); // run once immediately on enable
    return () => clearInterval(interval);
  }, [autoTradeEnabled, evaluateAndTrade]);

  useEffect(() => {
    if (!autoTradeEnabled) return;
    // Check stop-loss / take-profit every 15 seconds
    const interval = setInterval(monitorPositions, 15_000);
    return () => clearInterval(interval);
  }, [autoTradeEnabled, monitorPositions]);
}
