"use client";
import { useCallback, useEffect, useRef } from "react";
import { useStore } from "./store";
import { computeIndicators, aggregateCandles } from "./indicators";
import { isMarketOpen } from "./utils";
import type { AISignal } from "./types";

/**
 * useAutoTradeEngine
 *
 * Evaluates signals and executes paper trades automatically.
 *
 * COST CONTROL:
 * - First tries to reuse signals already in the store (generated by manual scans).
 * - Only calls Claude directly when auto-trade is enabled AND no fresh signal exists
 *   for a ticker (fresh = < 5 minutes old). This means Claude is called at most once
 *   per ticker per 5-minute window, not every 30 seconds.
 */
export function useAutoTradeEngine() {
  const watchlist = useStore((s) => s.watchlist);
  const quotes = useStore((s) => s.quotes);
  const candlesMap = useStore((s) => s.candles);
  const news = useStore((s) => s.news);
  const tweets = useStore((s) => s.tweets);
  const anthropicKey = useStore((s) => s.anthropicKey);
  const cashBalance = useStore((s) => s.cashBalance);
  const positions = useStore((s) => s.positions);
  const signals = useStore((s) => s.signals);
  const autoTradeEnabled = useStore((s) => s.autoTradeEnabled);
  const settings = useStore((s) => s.autoTradeSettings);
  const autoTradeDailyPnl = useStore((s) => s.autoTradeDailyPnl);
  const autoTradeDailyCount = useStore((s) => s.autoTradeDailyCount);
  const autoTradeLastReset = useStore((s) => s.autoTradeLastReset);
  const trades = useStore((s) => s.trades);

  const unsettledFunds = useStore((s) => s.unsettledFunds);
  const cashAccount = useStore((s) => s.cashAccount);

  const executeOrder = useStore((s) => s.executeOrder);
  const addSignal = useStore((s) => s.addSignal);
  const addAutoTradeLog = useStore((s) => s.addAutoTradeLog);
  const resetAutoTradeDailyStats = useStore((s) => s.resetAutoTradeDailyStats);
  const setAutoTradeEnabled = useStore((s) => s.setAutoTradeEnabled);
  const setAutoTradeSettings = useStore((s) => s.setAutoTradeSettings);
  const recordAnthropicUsage = useStore((s) => s.recordAnthropicUsage);
  const setApiCreditError = useStore((s) => s.setApiCreditError);
  const setOutOfFundsError = useStore((s) => s.setOutOfFundsError);
  const sweepSettledFunds = useStore((s) => s.sweepSettledFunds);

  const lastTradeTime = useRef<Record<string, number>>({});
  const lastMarketClosedLog = useRef<number>(0);
  const holdCache = useRef<Record<string, number>>({});

  // Reset daily counters at midnight
  useEffect(() => {
    const today = new Date().toISOString().split("T")[0];
    if (autoTradeLastReset !== today) resetAutoTradeDailyStats();
  }, [autoTradeLastReset, resetAutoTradeDailyStats]);

  const evaluateSignal = useCallback(
    async (ticker: string): Promise<AISignal | null> => {
      // If we hold a position in this ticker, always get a fresh signal
      // so the AI can recommend closing it — don't reuse stale BUY signals
      const holdingPosition = useStore.getState().positions.some(
        (p) => p.ticker === ticker && p.quantity > 0
      );

      if (!holdingPosition) {
        // 1. Check if there is a recent signal already in the store (< 5 min old)
        const FRESH_MS = 5 * 60 * 1000;
        const existing = signals.find(
          (s) => s.ticker === ticker && Date.now() - s.timestamp < FRESH_MS
        );
        if (existing) return existing;

        // 1b. Skip if this ticker returned HOLD recently (saves API credits)
        const HOLD_TTL = 5 * 60 * 1000;
        if (holdCache.current[ticker] && Date.now() - holdCache.current[ticker] < HOLD_TTL) {
          return null;
        }
      }

      // 2. No fresh signal — call Claude, but only if API key is present
      if (!anthropicKey) return null;

      const quote = quotes[ticker];
      const candles = candlesMap[ticker];
      if (!quote || !candles?.length) return null;

      const ind = computeIndicators(candles);

      // Multi-timeframe: aggregate 5m candles into 15m (every 3 candles)
      const candles15m = aggregateCandles(candles, 3);
      const ind15m = computeIndicators(candles15m);
      const trend15m = ind15m.macd !== undefined && ind15m.macdSignal !== undefined
        ? ind15m.macd > ind15m.macdSignal ? "bullish" : ind15m.macd < ind15m.macdSignal ? "bearish" : "neutral"
        : "N/A";

      // Recent win rate feedback loop
      const todayStart = new Date();
      todayStart.setHours(0, 0, 0, 0);
      const todayTrades = trades.filter((t) => t.exitTime >= todayStart.getTime());
      const recentWinRate = todayTrades.length > 0
        ? todayTrades.filter((t) => t.pnl > 0).length / todayTrades.length
        : 0;
      const recentTradeCount = todayTrades.length;

      const tickerNews = news
        .filter((n) => !n.ticker || n.ticker === ticker)
        .slice(0, 3)
        .map((n) => n.headline)
        .join("; ");

      const tickerTweets = tweets.filter((t) => t.tickers.includes(ticker)).slice(0, 5);
      const xSentimentSummary = tickerTweets.length
        ? tickerTweets
            .map((t) => `${t.sentiment} (${t.likes}❤): "${t.text.slice(0, 80)}..."`)
            .join(" | ")
        : null;

      // Check if we already hold a position in this ticker
      const existingPosition = useStore.getState().positions.find(
        (p) => p.ticker === ticker && p.quantity > 0
      );
      const currentPosition = existingPosition
        ? {
            side: existingPosition.side,
            qty: existingPosition.quantity,
            entryPrice: existingPosition.entryPrice,
            pnl: existingPosition.unrealizedPnl,
          }
        : null;

      try {
        const res = await fetch("/api/ai/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            ticker,
            price: quote.price,
            vwap: ind.vwap,
            rsi: ind.rsi,
            macd: ind.macd,
            macdSignal: ind.macdSignal,
            volume: quote.volume,
            relVolume: ind.relVolume,
            prevHigh: quote.high,
            prevLow: quote.low,
            sma20: ind.sma20,
            ema9: ind.ema9,
            bbUpper: ind.bbUpper,
            bbLower: ind.bbLower,
            news: tickerNews || null,
            xSentiment: xSentimentSummary,
            apiKey: anthropicKey,
            trend15m,
            rsi15m: ind15m.rsi,
            macd15m: trend15m,
            recentWinRate,
            recentTradeCount,
            allowShorts: settings.allowShorts,
            currentPosition,
          }),
        });
        const data = await res.json();
        if (data.creditError) {
          setApiCreditError(true);
          return null;
        }
        if (data.usage) {
          recordAnthropicUsage(data.usage.input_tokens ?? 0, data.usage.output_tokens ?? 0);
        }
        if (data.signal) {
          if (data.signal.signal === "HOLD") {
            holdCache.current[ticker] = Date.now(); // suppress re-calls for 5 min
          } else {
            addSignal(data.signal);
          }
          return data.signal;
        }
      } catch {}
      return null;
    },
    [signals, anthropicKey, quotes, candlesMap, news, tweets, trades, addSignal, recordAnthropicUsage, setApiCreditError]
  );

  const evaluateAndTrade = useCallback(async () => {
    if (!autoTradeEnabled) return;

    // Block live auto-trade unless explicitly enabled
    const { alpacaMode, alpacaLiveKey, alpacaLiveSecret } = useStore.getState();
    const isLive = alpacaMode === "live";
    if (isLive && !settings.allowLiveAutoTrade) return;
    if (isLive && (!alpacaLiveKey || !alpacaLiveSecret)) {
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: "Live auto-trade enabled but no live Alpaca keys are set. Add them in Settings.",
      });
      return;
    }

    // Market hours gate
    if (settings.marketHoursOnly && !isMarketOpen()) {
      const fiveMin = 5 * 60 * 1000;
      if (Date.now() - lastMarketClosedLog.current > fiveMin) {
        lastMarketClosedLog.current = Date.now();
        addAutoTradeLog({
          ticker: "SYSTEM",
          decision: "BLOCKED",
          reason: "Market is closed. Disable 'Market Hours Only' in Settings to trade outside hours.",
        });
      }
      return;
    }

    const { liveAccount } = useStore.getState();

    // ──────────────────────────────────────────────────────────────
    // PHASE 1: Close existing positions that should be sold.
    // This runs BEFORE daily-limit / funds checks — you must always
    // be able to exit a position regardless of those gates.
    // ──────────────────────────────────────────────────────────────
    // In live mode, fetch actual Alpaca positions — they are the source of truth
    let alpacaPositions: Array<{ symbol: string; qty: number; currentPrice: number; unrealizedPnl: number; unrealizedPnlPct: number; side: string; avgEntryPrice: number }> = [];
    if (isLive && alpacaLiveKey && alpacaLiveSecret) {
      try {
        const res = await fetch(
          `/api/trade/account?mode=live&apiKey=${encodeURIComponent(alpacaLiveKey)}&apiSecret=${encodeURIComponent(alpacaLiveSecret)}`
        );
        const data = await res.json();
        if (data.positions) alpacaPositions = data.positions;
      } catch {}
    }

    // Build a unified list of held positions
    // Live mode: use Alpaca positions as truth. Paper mode: use local store.
    const heldPositions: Array<{
      ticker: string; side: "LONG" | "SHORT"; quantity: number; entryPrice: number;
      currentPrice: number; unrealizedPnl: number; pnlPct: number;
      stopLoss?: number; takeProfit?: number; entryTime: number;
    }> = [];

    if (isLive) {
      for (const ap of alpacaPositions) {
        const localPos = positions.find((p) => p.ticker === ap.symbol && p.quantity > 0);
        heldPositions.push({
          ticker: ap.symbol,
          side: ap.side === "short" ? "SHORT" : "LONG",
          quantity: ap.qty,
          entryPrice: ap.avgEntryPrice,
          currentPrice: ap.currentPrice,
          unrealizedPnl: ap.unrealizedPnl,
          pnlPct: ap.unrealizedPnlPct,
          stopLoss: localPos?.stopLoss,
          takeProfit: localPos?.takeProfit,
          entryTime: localPos?.entryTime ?? Date.now() - 60000, // fallback: assume 1 min ago
        });
      }
    } else {
      for (const p of positions) {
        if (p.quantity <= 0) continue;
        const currentPrice = useStore.getState().quotes[p.ticker]?.price ?? p.currentPrice;
        heldPositions.push({
          ticker: p.ticker,
          side: p.side,
          quantity: p.quantity,
          entryPrice: p.entryPrice,
          currentPrice,
          unrealizedPnl: (currentPrice - p.entryPrice) * p.quantity * (p.side === "LONG" ? 1 : -1),
          pnlPct: p.entryPrice > 0 ? ((currentPrice - p.entryPrice) / p.entryPrice) * 100 * (p.side === "LONG" ? 1 : -1) : 0,
          stopLoss: p.stopLoss,
          takeProfit: p.takeProfit,
          entryTime: p.entryTime,
        });
      }
    }

    for (const pos of heldPositions) {
      if (pos.side !== "LONG") continue;

      const currentPrice = pos.currentPrice;
      const pnlPct = pos.pnlPct;
      const liveQty = pos.quantity;

      // Simple rule-based sell triggers that don't need the AI:
      let sellReason: string | null = null;

      // Stop-loss
      if (pos.stopLoss && currentPrice > 0 && currentPrice <= pos.stopLoss) {
        sellReason = `Stop-loss hit @ $${currentPrice.toFixed(2)} (stop $${pos.stopLoss.toFixed(2)})`;
      }
      // Take-profit
      else if (pos.takeProfit && currentPrice > 0 && currentPrice >= pos.takeProfit) {
        sellReason = `Take-profit hit @ $${currentPrice.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
      }
      // Max loss — hard cut at 3% loss, no AI needed
      else if (currentPrice > 0 && pnlPct <= -3) {
        sellReason = `Max loss cut @ $${currentPrice.toFixed(2)} (${pnlPct.toFixed(1)}% loss, entry $${pos.entryPrice.toFixed(2)})`;
      }
      // Time-based exit
      else if (settings.maxPositionMinutes > 0) {
        const ageMin = (Date.now() - pos.entryTime) / 60000;
        if (ageMin >= settings.maxPositionMinutes) {
          sellReason = `Time exit after ${ageMin.toFixed(0)} min (max ${settings.maxPositionMinutes})`;
        }
      }

      // If no rule-based trigger, ask the AI (if we have data)
      if (!sellReason) {
        const quote = useStore.getState().quotes[pos.ticker];
        const candles = useStore.getState().candles[pos.ticker];
        // Can call AI even without full candle data — send what we have
        if (anthropicKey && (quote || currentPrice > 0)) {
          const ind = candles?.length ? computeIndicators(candles) : {};
          const candles15m = candles?.length ? aggregateCandles(candles, 3) : [];
          const ind15m = candles15m.length ? computeIndicators(candles15m) : {};
          const trend15m = ind15m.macd !== undefined && ind15m.macdSignal !== undefined
            ? ind15m.macd > ind15m.macdSignal ? "bullish" : ind15m.macd < ind15m.macdSignal ? "bearish" : "neutral"
            : "N/A";

          try {
            const res = await fetch("/api/ai/analyze", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                ticker: pos.ticker,
                price: currentPrice || quote?.price || pos.entryPrice,
                vwap: ind.vwap,
                rsi: ind.rsi,
                macd: ind.macd,
                macdSignal: ind.macdSignal,
                volume: quote?.volume,
                relVolume: ind.relVolume,
                prevHigh: quote?.high,
                prevLow: quote?.low,
                sma20: ind.sma20,
                ema9: ind.ema9,
                bbUpper: ind.bbUpper,
                bbLower: ind.bbLower,
                news: null,
                xSentiment: null,
                apiKey: anthropicKey,
                trend15m,
                rsi15m: ind15m.rsi,
                macd15m: trend15m,
                recentWinRate: 0,
                recentTradeCount: 0,
                allowShorts: settings.allowShorts,
                currentPosition: {
                  side: pos.side,
                  qty: liveQty,
                  entryPrice: pos.entryPrice,
                  pnl: pos.unrealizedPnl,
                },
              }),
            });
            const data = await res.json();
            if (data.usage) recordAnthropicUsage(data.usage.input_tokens ?? 0, data.usage.output_tokens ?? 0);
            if (data.signal?.signal === "SELL") {
              sellReason = `AI recommends exit: ${data.signal.reason}`;
            }
          } catch {}
        }
      }

      if (sellReason) {
        const closePrice = currentPrice || pos.entryPrice;
        if (isLive) {
          try {
            // Use Alpaca's close-position endpoint — no qty needed, closes entire position
            const res = await fetch("/api/trade/close-position", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                mode: "live",
                apiKey: alpacaLiveKey,
                apiSecret: alpacaLiveSecret,
                symbol: pos.ticker,
              }),
            });
            const data = await res.json();
            if (!res.ok || data.error) {
              addAutoTradeLog({ ticker: pos.ticker, decision: "BLOCKED", reason: `Failed to close: ${data.error ?? "unknown"}` });
              continue;
            }
          } catch (err) {
            addAutoTradeLog({ ticker: pos.ticker, decision: "BLOCKED", reason: `Network error closing: ${err instanceof Error ? err.message : "unknown"}` });
            continue;
          }
        }
        executeOrder({ ticker: pos.ticker, side: "SELL", type: "MARKET", quantity: pos.quantity, price: closePrice });
        lastTradeTime.current[pos.ticker] = Date.now();
        addAutoTradeLog({
          ticker: pos.ticker,
          decision: "EXECUTED",
          reason: `CLOSED: ${sellReason}`,
          sharesQty: liveQty,
        });
      }
    }

    // ──────────────────────────────────────────────────────────────
    // PHASE 2: Open new positions (subject to daily limits / funds)
    // ──────────────────────────────────────────────────────────────

    // Daily circuit breakers — only gate NEW opens, not closes
    if (autoTradeDailyCount >= settings.maxDailyTrades) return;
    if (autoTradeDailyPnl <= -settings.maxDailyLoss) {
      setAutoTradeEnabled(false);
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: `Daily loss limit of $${settings.maxDailyLoss} reached. Auto-trade disabled.`,
      });
      return;
    }

    // Don't open new live positions until account data has loaded
    if (isLive && !liveAccount) return;

    const portfolioValue = isLive && liveAccount
      ? Math.max(liveAccount.portfolioValue, liveAccount.equity, liveAccount.cash)
      : cashBalance + positions.reduce((sum, p) => sum + p.currentPrice * p.quantity, 0);
    const unsettledTotal = (!isLive && cashAccount)
      ? unsettledFunds.filter((f) => f.settlesAt > Date.now()).reduce((sum, f) => sum + f.amount, 0)
      : 0;
    const availableCash = isLive && liveAccount
      ? Math.max(liveAccount.buyingPower, liveAccount.cash, 0)
      : cashBalance - unsettledTotal;

    if (!isLive && availableCash <= 0) {
      addAutoTradeLog({
        ticker: "SYSTEM",
        decision: "BLOCKED",
        reason: `No paper funds available ($${availableCash.toFixed(2)}). Will retry next cycle.`,
      });
      return;
    }

    for (const ticker of watchlist.slice(0, 5)) {
      // Per-ticker cooldown
      const cooldownMs = settings.cooldownMinutes * 60 * 1000;
      if (Date.now() - (lastTradeTime.current[ticker] ?? 0) < cooldownMs) continue;

      // Skip tickers we already hold — closing was handled in Phase 1
      const stillHeld = isLive
        ? alpacaPositions.some((a) => a.symbol === ticker)
        : positions.some((p) => p.ticker === ticker && p.quantity > 0);
      if (stillHeld) continue;

      const signal = await evaluateSignal(ticker);
      if (!signal) continue;

      if (signal.signal === "HOLD") {
        addAutoTradeLog({ ticker, decision: "SKIPPED", reason: "Signal is HOLD — no trade.", signal });
        continue;
      }

      // Volume filter — skip thin markets
      const quote = useStore.getState().quotes[ticker];
      const candles = useStore.getState().candles[ticker];
      const ind = candles?.length ? computeIndicators(candles) : {};
      if (ind.relVolume !== undefined && ind.relVolume < 0.5) {
        addAutoTradeLog({ ticker, decision: "SKIPPED", reason: `Volume too thin (${ind.relVolume.toFixed(2)}x avg). Waiting for liquidity.`, signal });
        continue;
      }

      // Confidence gate
      if (signal.confidence < settings.confidenceThreshold) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: `Confidence ${(signal.confidence * 100).toFixed(0)}% below threshold ${(settings.confidenceThreshold * 100).toFixed(0)}%.`,
          signal,
        });
        continue;
      }

      // Shorts gate
      if (signal.signal === "SELL" && !settings.allowShorts) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: "SELL signal skipped — shorts disabled.",
          signal,
        });
        continue;
      }

      // X confirmation gate
      if (settings.requireXConfirmation) {
        const tickerTweets = tweets.filter((t) => t.tickers.includes(ticker));
        if (tickerTweets.length > 0) {
          const bull = tickerTweets.filter((t) => t.sentiment === "bullish").length;
          const bear = tickerTweets.filter((t) => t.sentiment === "bearish").length;
          const agrees =
            (signal.signal === "BUY" && bull > bear) ||
            (signal.signal === "SELL" && bear > bull);
          if (!agrees) {
            addAutoTradeLog({
              ticker,
              decision: "SKIPPED",
              reason: `X sentiment doesn't confirm ${signal.signal} (bull:${bull} bear:${bear}).`,
              signal,
            });
            continue;
          }
        }
      }

      // Position sizing — dollar-based (supports fractional shares)
      const riskPerShare = ind.atr
        ? ind.atr * 2
        : Math.abs(signal.entry - signal.stop_loss);
      if (riskPerShare <= 0) continue;

      const drawdownFactor = autoTradeDailyPnl < -(settings.maxDailyLoss * 0.5) ? 0.5 : 1.0;

      // Compute notional $ amount, then derive fractional qty from entry price
      let notional = (portfolioValue * (settings.riskPerTrade / 100) * drawdownFactor * signal.entry) / riskPerShare;
      notional = Math.min(notional, settings.maxPositionSize, availableCash * 0.95);
      notional = Math.max(0, notional);

      if (notional < 1) {
        addAutoTradeLog({
          ticker,
          decision: "SKIPPED",
          reason: `Position too small ($${notional.toFixed(2)}). Check cash balance or risk settings.`,
          signal,
        });
        continue;
      }

      // Fractional qty for paper; notional for live Alpaca
      const fractionalQty = +(notional / signal.entry).toFixed(4);

      // Execute — route to Alpaca in live mode, local state in paper mode
      if (isLive) {
        const { alpacaLiveKey: liveKey, alpacaLiveSecret: liveSecret } = useStore.getState();
        try {
          const res = await fetch("/api/trade/order", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              mode: "live",
              apiKey: liveKey,
              apiSecret: liveSecret,
              symbol: ticker,
              side: signal.signal === "BUY" ? "BUY" : "SELL",
              type: "MARKET",
              notional: +notional.toFixed(2),
            }),
          });
          const data = await res.json();
          if (!res.ok || data.error) {
            const errMsg: string = data.error ?? "unknown error";
            // Alpaca rejects shorts on cash/non-margin accounts — auto-disable to stop retrying
            if (/short|not allowed to short/i.test(errMsg)) {
              setAutoTradeSettings({ allowShorts: false });
              addAutoTradeLog({
                ticker,
                decision: "BLOCKED",
                reason: `Shorting not allowed on this Alpaca account. 'Allow Shorts' has been disabled automatically. Enable a margin account at alpaca.markets if you want to short.`,
                signal,
              });
            } else {
              addAutoTradeLog({
                ticker,
                decision: "BLOCKED",
                reason: `Alpaca rejected order: ${errMsg}`,
                signal,
              });
            }
            continue;
          }
          // Record locally for the journal using fractional qty
          executeOrder({
            ticker,
            side: signal.signal === "BUY" ? "BUY" : "SELL",
            type: "MARKET",
            quantity: fractionalQty,
            price: signal.entry,
            stopPrice: signal.stop_loss,
            takeProfitPrice: signal.target,
          });
        } catch (err) {
          addAutoTradeLog({
            ticker,
            decision: "BLOCKED",
            reason: `Network error submitting live order: ${err instanceof Error ? err.message : "unknown"}`,
            signal,
          });
          continue;
        }
      } else {
        executeOrder({
          ticker,
          side: signal.signal === "BUY" ? "BUY" : "SELL",
          type: "MARKET",
          quantity: fractionalQty,
          price: signal.entry,
          stopPrice: signal.stop_loss,
          takeProfitPrice: signal.target,
        });
      }

      lastTradeTime.current[ticker] = Date.now();

      addAutoTradeLog({
        ticker,
        decision: "EXECUTED",
        reason: `${signal.signal} ${fractionalQty}sh ($${notional.toFixed(2)}) @ $${signal.entry.toFixed(2)} | Stop $${signal.stop_loss.toFixed(2)} | Target $${signal.target.toFixed(2)} | ${(signal.confidence * 100).toFixed(0)}% confidence. ${signal.reason}`,
        signal,
        sharesQty: fractionalQty,
        positionSize: notional,
      });
    }
  }, [
    autoTradeEnabled, settings, autoTradeDailyCount, autoTradeDailyPnl,
    watchlist, cashBalance, positions, tweets, evaluateSignal,
    executeOrder, addAutoTradeLog, setAutoTradeEnabled, setAutoTradeSettings, setOutOfFundsError,
    unsettledFunds, cashAccount, anthropicKey, recordAnthropicUsage,
  ]);

  const monitorPositions = useCallback(async () => {
    sweepSettledFunds();
    const { positions, quotes, alpacaMode, alpacaLiveKey, alpacaLiveSecret } = useStore.getState();
    const isLive = alpacaMode === "live";
    const now = Date.now();

    // In live mode, fetch fresh prices from Alpaca positions endpoint
    let livePrices: Record<string, number> = {};
    if (isLive && alpacaLiveKey && alpacaLiveSecret) {
      try {
        const res = await fetch(
          `/api/trade/account?mode=live&apiKey=${encodeURIComponent(alpacaLiveKey)}&apiSecret=${encodeURIComponent(alpacaLiveSecret)}`
        );
        const data = await res.json();
        if (data.positions) {
          for (const p of data.positions) {
            livePrices[p.symbol] = p.currentPrice;
          }
        }
      } catch {
        // Fall back to local quotes/entry price
      }
    }

    // Helper: close a position via Alpaca's close-position endpoint (no qty needed)
    const submitLiveClose = async (ticker: string, _side: string, _qty: number): Promise<boolean> => {
      if (!isLive) return true; // paper mode — local executeOrder handles it
      try {
        const res = await fetch("/api/trade/close-position", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            mode: "live",
            apiKey: alpacaLiveKey,
            apiSecret: alpacaLiveSecret,
            symbol: ticker,
          }),
        });
        const data = await res.json();
        if (!res.ok || data.error) {
          addAutoTradeLog({ ticker, decision: "BLOCKED", reason: `Failed to close live position: ${data.error ?? "unknown error"}` });
          return false;
        }
        return true;
      } catch (err) {
        addAutoTradeLog({ ticker, decision: "BLOCKED", reason: `Network error closing live position: ${err instanceof Error ? err.message : "unknown"}` });
        return false;
      }
    };

    // End-of-day close: force-close all positions 15 min before 4pm ET
    const et = new Date(now);
    const etTime = new Date(et.toLocaleString("en-US", { timeZone: "America/New_York" }));
    const etMinutes = etTime.getHours() * 60 + etTime.getMinutes();
    const isEodClose = etMinutes >= 15 * 60 + 45 && etMinutes < 16 * 60; // 3:45–4:00 PM ET

    for (const pos of positions) {
      if (pos.quantity <= 0) continue;
      // Price priority: live Alpaca price > local quotes > entry price
      const price = livePrices[pos.ticker] ?? quotes[pos.ticker]?.price ?? pos.currentPrice;
      const closeSide = pos.side === "LONG" ? "SELL" : "BUY";

      // End-of-day: close everything
      if (isEodClose) {
        const ok = await submitLiveClose(pos.ticker, closeSide, pos.quantity);
        if (ok) {
          executeOrder({ ticker: pos.ticker, side: closeSide, type: "MARKET", quantity: pos.quantity, price });
          addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason: `End-of-day close @ $${price.toFixed(2)} (3:45 PM ET cutoff).` });
        }
        continue;
      }

      // Time-based exit
      if (settings.maxPositionMinutes > 0) {
        const ageMinutes = (now - pos.entryTime) / 60000;
        if (ageMinutes >= settings.maxPositionMinutes) {
          const ok = await submitLiveClose(pos.ticker, closeSide, pos.quantity);
          if (ok) {
            executeOrder({ ticker: pos.ticker, side: closeSide, type: "MARKET", quantity: pos.quantity, price });
            addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason: `Time-based exit after ${ageMinutes.toFixed(0)} min (max ${settings.maxPositionMinutes} min).` });
          }
          continue;
        }
      }

      // Update trailing stop
      let activeStopLoss = pos.stopLoss;
      if (settings.trailingStopPct > 0 && pos.stopLoss !== undefined) {
        const trailFactor = settings.trailingStopPct / 100;
        if (pos.side === "LONG") {
          const trailedStop = price * (1 - trailFactor);
          if (trailedStop > (pos.trailingStop ?? pos.stopLoss ?? 0)) {
            useStore.setState((s) => ({
              positions: s.positions.map((p) =>
                p.id === pos.id ? { ...p, trailingStop: trailedStop } : p
              ),
            }));
            activeStopLoss = trailedStop;
          } else {
            activeStopLoss = pos.trailingStop ?? pos.stopLoss;
          }
        } else {
          const trailedStop = price * (1 + trailFactor);
          if (trailedStop < (pos.trailingStop ?? pos.stopLoss ?? Infinity)) {
            useStore.setState((s) => ({
              positions: s.positions.map((p) =>
                p.id === pos.id ? { ...p, trailingStop: trailedStop } : p
              ),
            }));
            activeStopLoss = trailedStop;
          } else {
            activeStopLoss = pos.trailingStop ?? pos.stopLoss;
          }
        }
      }

      // Partial take-profit: sell 50% when price hits midpoint between entry and target
      if (settings.partialTpEnabled && !pos.partialTpTaken && pos.takeProfit) {
        const midpoint = pos.side === "LONG"
          ? pos.entryPrice + (pos.takeProfit - pos.entryPrice) * 0.5
          : pos.entryPrice - (pos.entryPrice - pos.takeProfit) * 0.5;
        const hitMidpoint = pos.side === "LONG" ? price >= midpoint : price <= midpoint;
        if (hitMidpoint && pos.quantity >= 2) {
          const halfQty = Math.floor(pos.quantity / 2);
          const ok = await submitLiveClose(pos.ticker, closeSide, halfQty);
          if (ok) {
            executeOrder({ ticker: pos.ticker, side: closeSide, type: "MARKET", quantity: halfQty, price });
            useStore.setState((s) => ({
              positions: s.positions.map((p) =>
                p.id === pos.id
                  ? { ...p, partialTpTaken: true, stopLoss: pos.entryPrice, trailingStop: pos.entryPrice }
                  : p
              ),
            }));
            addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason: `Partial TP: sold ${halfQty} shares @ $${price.toFixed(2)} (midpoint $${midpoint.toFixed(2)}). Stop moved to breakeven $${pos.entryPrice.toFixed(2)}.` });
          }
          continue;
        }
      }

      // Stop-loss / take-profit check
      let reason: string | null = null;
      if (pos.side === "LONG") {
        if (activeStopLoss && price <= activeStopLoss) {
          reason = `Stop-loss triggered @ $${price.toFixed(2)} (stop $${activeStopLoss.toFixed(2)})`;
        } else if (pos.takeProfit && price >= pos.takeProfit) {
          reason = `Take-profit triggered @ $${price.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
        }
      } else {
        if (activeStopLoss && price >= activeStopLoss) {
          reason = `Stop-loss triggered @ $${price.toFixed(2)} (stop $${activeStopLoss.toFixed(2)})`;
        } else if (pos.takeProfit && price <= pos.takeProfit) {
          reason = `Take-profit triggered @ $${price.toFixed(2)} (target $${pos.takeProfit.toFixed(2)})`;
        }
      }

      if (reason) {
        const ok = await submitLiveClose(pos.ticker, closeSide, pos.quantity);
        if (ok) {
          executeOrder({ ticker: pos.ticker, side: closeSide, type: "MARKET", quantity: pos.quantity, price });
          addAutoTradeLog({ ticker: pos.ticker, decision: "EXECUTED", reason });
        }
      }
    }
  }, [executeOrder, addAutoTradeLog, settings, sweepSettledFunds]);

  useEffect(() => {
    if (!autoTradeEnabled) return;
    // Clear stale error banners when re-enabled
    setOutOfFundsError(false);
    // Delay the first run by 3s to let liveAccount sync complete
    const startup = setTimeout(evaluateAndTrade, 3000);
    const interval = setInterval(evaluateAndTrade, 60_000);
    return () => { clearTimeout(startup); clearInterval(interval); };
  }, [autoTradeEnabled, evaluateAndTrade, setOutOfFundsError]);

  useEffect(() => {
    if (!autoTradeEnabled) return;
    // Check stop-loss / take-profit every 15 seconds
    const interval = setInterval(monitorPositions, 15_000);
    return () => clearInterval(interval);
  }, [autoTradeEnabled, monitorPositions]);
}
